sudo: false
language: node_js

services:
- docker

addons:
  hosts:
  - mariadb.example.com

before_script:
# Disable services enabled by default
- sudo /etc/init.d/mysql stop
before_install:
- chmod +x .travis/script.sh

install:
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  # generate SSL certificates
  - mkdir tmp
  - chmod +x .travis/gen-ssl.sh
  - chmod +x .travis/build/build.sh
  - chmod +x .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export PROJ_PATH=`pwd`
  - export SSLCERT=$PROJ_PATH/tmp
  - export TEST_SSL_CA_FILE=$SSLCERT/server.crt
  - export TEST_SSL_CLIENT_KEY_FILE=$SSLCERT/client.key
  - export TEST_SSL_CLIENT_CERT_FILE=$SSLCERT/client.crt
  - export TEST_SSL_CLIENT_KEYSTORE_FILE=$SSLCERT/client-keystore.p12

env:
  global:
  - TEST_PORT=3305
  - TEST_HOST=mariadb.example.com
  - MUST_USE_TCPIP=1
  - RUN_LONG_TEST=1

matrix:
  allow_failures:
  - node_js: "12"
    env: DB=build SKIP_LEAK=1
  include:
  - node_js: "12"
    env: DB=build SKIP_LEAK=1
  - node_js: "8"
    env: DB=mariadb:10.4
  - node_js: "10"
    env: DB=mariadb:10.4
  - node_js: "12"
    env: DB=mariadb:10.4 SKIP_LEAK=1 ADDITIONAL_CONF=--version=10.4.199
  - node_js: "12"
    env: DB=mariadb:10.4 SKIP_LEAK=1 TEST_COLLATION=cp1251_general_ci
  - node_js: "12"
    env: DB=mariadb:10.4 LINT=1 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mariadb:10.4 BENCH=1 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mariadb:10.4 MAXSCALE_VERSION=2.2.9 TEST_PORT=4007 TEST_USER=bob TEXT_DATABASE=test2 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mariadb:5.5 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mariadb:10.0 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mariadb:10.1 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mariadb:10.2 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mariadb:10.3 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mysql:5.5 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mysql:5.6 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mysql:5.7 SKIP_LEAK=1
  - node_js: "12"
    env: DB=mysql:8.0 SKIP_LEAK=1

notifications:
  email: false

script:
- npm install
- npm install nyc -g
- travis_retry .travis/script.sh

after_success:
- if [ -z "$BENCH" ] ; then npm run coverage:report; fi